# Generated by Django 4.2.7 on 2026-03-09 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inventory_status', 'Inventory Status Report'), ('inventory_utilization', 'Inventory Utilization Report'), ('stock_summary', 'Stock Summary Report'), ('event_resources', 'Event Resources Report'), ('booking_summary', 'Booking Summary Report'), ('custom', 'Custom Report')], max_length=30)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'generated_at'], name='reports_report__bb4969_idx'), models.Index(fields=['generated_by', 'generated_at'], name='reports_generat_a180de_idx')],
            },
        ),
    ]
